---
title: "problem3"
output: github_document
date: "2024-10-02"
---
```{r}
bakers_data = read_csv("./data/bakers.csv", 
                       col_names=TRUE,
                       na=c("NA",".","")) |>
  janitor::clean_names() |>
  separate(baker_name,into=c("baker","rest_of_the_name"), sep=" ", remove=FALSE) |>
  select(-rest_of_the_name)

bakes_data = read_csv("./data/bakes.csv", 
                      col_names=TRUE,
                      na=c("NA",".","")) |> 
  janitor::clean_names() 

bakers_bakes_df = 
  full_join(bakers_data, bakes_data, by = c("baker", "series")) |>
  relocate(baker_name,baker,baker_age,baker_occupation,hometown,series,episode,signature_bake,show_stopper)

#test
#test <- anti_join(bakers_data, bakes_data, by = c("baker", "series"))
#test2 <- anti_join(bakes_data, bakers_data, by = c("baker", "series"))
#write_csv(bakers_bakes_df,file="./data/bakers_bakes_df.csv")
```


```{r}
results_data = read_csv("./data/results.csv", 
                        col_names=TRUE,
                        na=c("NA",".","")) |>
  janitor::clean_names() 

bakers_bakes_results_df = 
full_join(bakers_bakes_df, results_data, by=c("baker","series","episode"))
write_csv(bakers_bakes_results_df,file="./data/bakers_bakes_results_df.csv")

#test
#test3 <- anti_join(bakers_bakes_df, results_data, by = c("baker","series","episode"))
#test4 <- anti_join(results_data, bakers_bakes_df,by = c("baker","series","episode"))

```

```{r}
table = bakers_bakes_results_df |>  filter(result==c("WINNER","STAR BAKER")) |>
  filter(series >= 5) |>
  arrange(series,episode)
write_csv(table,file="./data/table.csv")

```

```{r}
viewers_df = read_csv("./data/viewers.csv", 
                        col_names=TRUE,
                        na=c("NA",".","")) |>
  janitor::clean_names() 

print(viewers_df)
round(mean(pull(viewers_df, series_1), na.rm=TRUE), digits=2)
round(mean(pull(viewers_df, series_5), na.rm=TRUE), digits=2)

```

